name: Dev
favicon: null
layout_spectrum: 0.76877
typography_spectrum: 0.16968593979254365
title: Original Piano Compositions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.42667431011796
  rhythmicContrast: 0.75
purpose: []
